module.exports = {
  home: {
    hero: {
      badge: "Practical learning. Real-world skills.",
      title: "Learn E-Commerce.",
      highlight: "Grow",
      titleSuffix: "Your Business.",
      subtitle: "Master Amazon & E-Commerce with Practical Training",
      description: "Sky Birds Solution helps beginners, aspiring sellers, business owners, and professionals understand online marketplaces through practical, career-focused learning.",
      primaryCta: "Explore Courses",
      secondaryCta: "About Sky Birds",
      trustPoints: ["Practical Training", "Amazon & E-Commerce", "Learn at Your Pace"],
      imageEyebrow: "Your learning journey",
      imageTitle: "From Learning to Doing.",
      imageDescription: "Build practical knowledge for today's online marketplace.",
      floatOneTitle: "Learn at your pace",
      floatOneText: "Flexible online learning",
      floatTwoTitle: "E-Commerce Skills",
      floatTwoText: "Learn • Apply • Grow",
    },
    featured: {
      eyebrow: "Start learning",
      title: "Featured Video Courses",
      description: "Explore training designed to help you understand online selling and marketplace operations.",
      buttonLabel: "See all courses",
    },
    learning: {
      eyebrow: "Learn with purpose",
      title: "Practical learning for every stage of your e-commerce journey",
      paragraph1: "Our programs are designed to support learners at different stages of their e-commerce journey, that varies from introductory concepts to advanced business strategies.",
      paragraph2: "We believe learning at Sky Birds Solution should be practical, accessible, and emphasized on real-world skills. Our approach is towards helping learners understand concepts and develop the confidence to apply their knowledge.",
      buttonLabel: "Find your course",
    },
    faq: {
      eyebrow: "Need to know",
      title: "Frequently Asked Questions",
      description: "Quick answers about learning Amazon selling and e-commerce with Sky Birds Solution.",
    },
    cta: {
      eyebrow: "Your next chapter starts here",
      title: "Start your E-Commerce Learning Journey Today",
      paragraph2: "Explore our e-commerce classes, discover our Amazon training programs, and take the next step towards building your digital business knowledge with Sky Birds Solution.",
      primaryLabel: "Explore Courses",
      secondaryLabel: "Contact Us",
    },
  },
  about: {
    hero: {
      badge: "About Sky Birds Solution",
      title: "Empowering Sellers.",
      highlight: "Growing Businesses.",
      description: "Sky Birds Solution is a growth-oriented E-Commerce agency in India, committed to empowering online sellers. From account setup and cataloguing to ads management and practical training, our in-house experts bring essential services together under one roof.",
      primaryCta: "Explore Our Courses",
      secondaryCta: "Talk to Our Team",
    },
  },
  seo: {
    defaultTitle: "Sky Birds Solution | E-Commerce Learning",
    defaultDescription: "Practical e-commerce and marketplace training for Amazon, Flipkart and Meesho sellers.",
    defaultKeywords: "Amazon seller course, e-commerce training, marketplace selling, Sky Birds Solution",
    pages: {
      home: { title: "Sky Birds Solution | E-Commerce Learning", description: "Practical e-commerce and marketplace training for Amazon, Flipkart and Meesho sellers." },
      about: { title: "About Sky Birds Solution", description: "Learn about Sky Birds Solution and its practical e-commerce learning approach." },
      contact: { title: "Contact Sky Birds Solution", description: "Contact Sky Birds Solution for seller support, courses and e-commerce training." },
      courses: { title: "E-Commerce Courses | Sky Birds Solution", description: "Explore practical marketplace courses." },
      watch: { title: "Watch Course | Sky Birds Solution", description: "Watch your purchased course lessons." },
      default: { title: "Sky Birds Solution", description: "Practical e-commerce learning." },
    },
  },
  support: {
    email: "support@skybirds.in",
    mobile: "+91 98765 43210 / +91 80000 12345",
    location: "SkyBirds E-Commerce Academy, Cyber City, Sector 24, Gurugram, Haryana - 122002",
    heading: "How Can Our Marketplace Team Help You?",
    description: "Have questions about our video courses, seller onboarding services, or account management? Send us a message and our specialists will respond promptly.",
    responseTime: "Typical response time: Under 4 business hours",
  },
  legal: {
    privacy: "Privacy Policy\n\nManage your privacy policy from the admin panel.",
    terms: "Terms & Conditions\n\nManage your terms & conditions from the admin panel.",
  },
};
